apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ise-msa-demo
build:
  artifacts:
    - image: frontend
      context: src/frontend
      docker:
        dockerfile: Dockerfile
    - image: posts
      context: src/posts
      docker:
        dockerfile: Dockerfile
    - image: users
      context: src/users
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - src/frontend/deployment.yaml
    - src/posts/deployment.yaml
    - src/users/deployment.yaml
# portForward:
#   - resourceType: service
#     resourceName: src-frontend
#     port: 17001
#   - resourceType: service
#     resourceName: src-products
#     port: 17002
#   - resourceType: service
#     resourceName: gateway
#     port: 17000

