apiVersion: v1
kind: Service
metadata:
  name: src-products
  labels:
    app: src-products
spec:
  ports:
  - port: 17002
    protocol: TCP
  clusterIP: None
  selector:
    app: src-products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-products
  labels:
    app: src-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-products
  template:
    metadata:
      labels:
        app: src-products
    spec:
      containers:
      - name: src-products
        image: src-products
